FROM ghcr.io/hiway-media/teamcity-agent-2023.11.3
#
USER root
RUN apt-get update
RUN apt-get -y install gitlab-cli unzip wget
# unzip wget nano
RUN wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip
RUN mkdir -p ~/Android/Sdk/cmdline-tools
RUN unzip commandlinetools.zip -d ~/Android/Sdk/cmdline-tools
RUN mv ~/Android/Sdk/cmdline-tools/cmdline-tools ~/Android/Sdk/cmdline-tools/latest
#
#RUN export ANDROID_SDK_ROOT=~/Android/Sdk
#RUN export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
#RUN export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
##
RUN echo $PATH
#ENV ANDROID_SDK_ROOT=~/Android/Sdk
#ENV PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
#ENV PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
RUN echo "export ANDROID_SDK_ROOT=~/Android/Sdk" >> ~/.bashrc
RUN echo "export ANDPATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> ~/.bashrc
RUN echo "export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools" >> ~/.bashrc
RUN cat ~/.bashrc
RUN echo $PATH
RUN . ~/.bashrc
##
RUN sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
#