FROM ghcr.io/hiway-media/teamcity-agent-latest
#
USER root
#
RUN apt-get update
RUN apt-get -y install gitlab-cli unzip wget android-sdk
#
# unzip wget nano
#RUN wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O commandlinetools.zip
#RUN mkdir -p ~/Android/Sdk/cmdline-tools
#RUN unzip commandlinetools.zip -d ~/Android/Sdk/cmdline-tools
#RUN mv ~/Android/Sdk/cmdline-tools/cmdline-tools ~/Android/Sdk/cmdline-tools/latest
##
#RUN export ANDROID_SDK_ROOT=$HOME/Android/Sdk
#RUN export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
#RUN export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
##
RUN sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"
#